// Unit guide:
// - Distances are feet; bot ground-speed UI values are miles per hour.
// - Other linear speeds are feet per second; accelerations and gravity are feet per second squared.
// - Durations are seconds. Damage values are hp, where 1 damage unit = 1 hp.
export const PHYSICAL_DAMAGE_DEFAULTS = {
  enabled: false,
  threshold: 28,
  significantHitsRequired: 2,
  resilience: 1,
  breakRadius: 0.24,
  primeMatchRadius: 0.42,
  maxBreakRadius: 0.48,
  maxPrimeMatchRadius: 0.84,
  maxRadiusDamageMultiplier: 10,
  radialFalloff: 0.55,
  maxPiecesPerBot: 5,
  minPieceTriangles: 18,
  maxPieceTriangles: 55000,
  impulseScale: 0.13,
  liftImpulse: 0.1,
  angularImpulse: 0.18,
  maxDebrisSpeed: 3.1,
  convexCollider: true,
  solidFill: true,
  interiorBreakInsideThreshold: 0.72,
  interiorBreakHitMultiplier: 2,
  failureThreshold: 70,
};

export const GAME_CONFIG = {
  ui: {
    arenaObjectMode: "none",
    arenaObjectCount: 4,
    cameraMode: "battle",
    cameraDistance: 6.2,
    cameraHeight: 2.8,
    arenaFov: 64,
    colliderViewMode: "all",
    useHaptics: true,
    invertOrbitY: true,
    lighting: 0.72,
    controlScheme: "tank",
    groundSpeed: 3.682,
    driveAcceleration: 8,
    turningTightness: 1,
    yawDamping: 1,
    weaponSpinUpSeconds: 3,
    spinnerImpactCapEnabled: false,
    spinnerImpactCap: 7.5,
    spinnerImpactScale: 1,
    spinnerGyroScale: 1,
    showAllBots: false,
    showColliders: false,
    teeterAssist: true,
    spinnerKnockback: true,
    plowDefence: true,
    softFloorCorrection: true,
    colliderCenterOfMass: false,
    sandboxMode: false,
    physicalDamageEnabled: true,
    showDamageEvents: true,
    physicsLogType: "all",
  },
  physics: {
    gravityY: -32.174,
  },
  battle: {
    matchDurationSeconds: 180,
    killSawStartRemainingSeconds: 60,
    killSawCalloutSeconds: 3.2,
  },
  botTuningFallbacks: {
    driveAcceleration: 8,
    turningTightness: 1,
    yawDamping: 1,
    weaponSpinUpSeconds: 0.2,
    botWeightLbs: 250,
  },
  damageEvents: {
    normalDisplaySeconds: 1,
    notableHpThreshold: 10,
    notableDisplaySeconds: 3,
    majorHpThreshold: 50,
    majorDisplaySeconds: 7,
  },
  fightIntro: {
    previewOrbitSeconds: 5,
    countdownBeatSeconds: 2,
    finalCalloutSeconds: 2,
    messageStartProgress: 0.3,
    finalCalloutReleaseProgress: 0.68,
    orbitSpeed: 0.34,
  },
  physicalDamage: PHYSICAL_DAMAGE_DEFAULTS,
  colliderTweaker: {
    editMode: "colliders",
    colliderViewMode: "all",
    geometryView: "everything",
    physicsTest: {
      velocityX: 0,
      velocityY: 0,
      velocityZ: 0,
      gravityY: -32.174,
      viewColliders: false,
      weaponOn: false,
      recentlyHit: false,
      selfRightingGrace: false,
    },
    physicalDamage: {
      rawDamage: 72,
      viewColliders: false,
    },
  },
};

export function applyControlDefaults(controlDefaults, root = document) {
  Object.entries(controlDefaults || {}).forEach(([id, value]) => {
    const element = root.getElementById?.(id) || root.querySelector?.(`#${id}`);
    if (!element) return;
    if (element.type === "checkbox") element.checked = Boolean(value);
    else element.value = String(value);
  });
}

export const MAIN_CONTROL_DEFAULTS = {
  "arena-object-mode": GAME_CONFIG.ui.arenaObjectMode,
  "arena-object-count": GAME_CONFIG.ui.arenaObjectCount,
  "arena-object-count-number": GAME_CONFIG.ui.arenaObjectCount,
  "camera-mode": GAME_CONFIG.ui.cameraMode,
  "camera-distance": GAME_CONFIG.ui.cameraDistance,
  "camera-distance-number": GAME_CONFIG.ui.cameraDistance,
  "camera-height": GAME_CONFIG.ui.cameraHeight,
  "camera-height-number": GAME_CONFIG.ui.cameraHeight,
  "arena-fov": GAME_CONFIG.ui.arenaFov,
  "arena-fov-number": GAME_CONFIG.ui.arenaFov,
  "collider-view-mode": GAME_CONFIG.ui.colliderViewMode,
  "use-haptics": GAME_CONFIG.ui.useHaptics,
  "invert-orbit-y": GAME_CONFIG.ui.invertOrbitY,
  lighting: GAME_CONFIG.ui.lighting,
  "lighting-number": GAME_CONFIG.ui.lighting,
  "control-scheme": GAME_CONFIG.ui.controlScheme,
  "ground-speed": GAME_CONFIG.ui.groundSpeed,
  "ground-speed-value": GAME_CONFIG.ui.groundSpeed,
  "drive-acceleration": GAME_CONFIG.ui.driveAcceleration,
  "drive-acceleration-value": GAME_CONFIG.ui.driveAcceleration,
  "turning-tightness": GAME_CONFIG.ui.turningTightness,
  "turning-tightness-value": GAME_CONFIG.ui.turningTightness,
  "yaw-damping": GAME_CONFIG.ui.yawDamping,
  "yaw-damping-value": GAME_CONFIG.ui.yawDamping,
  "weapon-spinup": GAME_CONFIG.ui.weaponSpinUpSeconds,
  "weapon-spinup-value": GAME_CONFIG.ui.weaponSpinUpSeconds,
  "spinner-impact-cap-enabled": GAME_CONFIG.ui.spinnerImpactCapEnabled,
  "spinner-impact-cap": GAME_CONFIG.ui.spinnerImpactCap,
  "spinner-impact-cap-value": GAME_CONFIG.ui.spinnerImpactCap,
  "spinner-impact-scale": GAME_CONFIG.ui.spinnerImpactScale,
  "spinner-impact-scale-value": GAME_CONFIG.ui.spinnerImpactScale,
  "spinner-gyro-scale": GAME_CONFIG.ui.spinnerGyroScale,
  "spinner-gyro-scale-value": GAME_CONFIG.ui.spinnerGyroScale,
  "show-all-bots": GAME_CONFIG.ui.showAllBots,
  "show-colliders": GAME_CONFIG.ui.showColliders,
  "teeter-assist-toggle": GAME_CONFIG.ui.teeterAssist,
  "spinner-knockback-toggle": GAME_CONFIG.ui.spinnerKnockback,
  "plow-defence-toggle": GAME_CONFIG.ui.plowDefence,
  "soft-floor-correction-toggle": GAME_CONFIG.ui.softFloorCorrection,
  "collider-com-toggle": GAME_CONFIG.ui.colliderCenterOfMass,
  "enable-damage-toggle": GAME_CONFIG.ui.sandboxMode,
  gravity: GAME_CONFIG.physics.gravityY,
  "gravity-number": GAME_CONFIG.physics.gravityY,
  "physical-damage-toggle": GAME_CONFIG.ui.physicalDamageEnabled,
  "physical-damage-threshold": PHYSICAL_DAMAGE_DEFAULTS.threshold,
  "physical-damage-threshold-value": PHYSICAL_DAMAGE_DEFAULTS.threshold,
  "physical-damage-hits-required": PHYSICAL_DAMAGE_DEFAULTS.significantHitsRequired,
  "physical-damage-hits-required-value": PHYSICAL_DAMAGE_DEFAULTS.significantHitsRequired,
  "physical-damage-resilience": PHYSICAL_DAMAGE_DEFAULTS.resilience,
  "physical-damage-resilience-value": PHYSICAL_DAMAGE_DEFAULTS.resilience,
  "physical-damage-radius": PHYSICAL_DAMAGE_DEFAULTS.breakRadius,
  "physical-damage-radius-value": PHYSICAL_DAMAGE_DEFAULTS.breakRadius,
  "physical-damage-match-radius": PHYSICAL_DAMAGE_DEFAULTS.primeMatchRadius,
  "physical-damage-match-radius-value": PHYSICAL_DAMAGE_DEFAULTS.primeMatchRadius,
  "physical-damage-max-radius": PHYSICAL_DAMAGE_DEFAULTS.maxBreakRadius,
  "physical-damage-max-radius-value": PHYSICAL_DAMAGE_DEFAULTS.maxBreakRadius,
  "physical-damage-max-match-radius": PHYSICAL_DAMAGE_DEFAULTS.maxPrimeMatchRadius,
  "physical-damage-max-match-radius-value": PHYSICAL_DAMAGE_DEFAULTS.maxPrimeMatchRadius,
  "physical-damage-max-radius-multiplier": PHYSICAL_DAMAGE_DEFAULTS.maxRadiusDamageMultiplier,
  "physical-damage-max-radius-multiplier-value": PHYSICAL_DAMAGE_DEFAULTS.maxRadiusDamageMultiplier,
  "physical-damage-impulse": PHYSICAL_DAMAGE_DEFAULTS.impulseScale,
  "physical-damage-impulse-value": PHYSICAL_DAMAGE_DEFAULTS.impulseScale,
  "physical-damage-max-pieces": PHYSICAL_DAMAGE_DEFAULTS.maxPiecesPerBot,
  "physical-damage-max-pieces-value": PHYSICAL_DAMAGE_DEFAULTS.maxPiecesPerBot,
  "physical-damage-failure-threshold": PHYSICAL_DAMAGE_DEFAULTS.failureThreshold,
  "physical-damage-failure-threshold-value": PHYSICAL_DAMAGE_DEFAULTS.failureThreshold,
  "physical-damage-convex": PHYSICAL_DAMAGE_DEFAULTS.convexCollider,
  "physical-damage-solid-fill": PHYSICAL_DAMAGE_DEFAULTS.solidFill,
  "show-damage-events-toggle": GAME_CONFIG.ui.showDamageEvents,
  "physics-log-type": GAME_CONFIG.ui.physicsLogType,
};

export const COLLIDER_TWEAKER_CONTROL_DEFAULTS = {
  "edit-mode": GAME_CONFIG.colliderTweaker.editMode,
  "collider-view-mode": GAME_CONFIG.colliderTweaker.colliderViewMode,
  "geometry-view": GAME_CONFIG.colliderTweaker.geometryView,
  "physics-velocity-x": GAME_CONFIG.colliderTweaker.physicsTest.velocityX,
  "physics-velocity-y": GAME_CONFIG.colliderTweaker.physicsTest.velocityY,
  "physics-velocity-z": GAME_CONFIG.colliderTweaker.physicsTest.velocityZ,
  "physics-gravity": GAME_CONFIG.colliderTweaker.physicsTest.gravityY,
  "physics-gravity-value": GAME_CONFIG.colliderTweaker.physicsTest.gravityY.toFixed(1),
  "physics-view-colliders": GAME_CONFIG.colliderTweaker.physicsTest.viewColliders,
  "physics-weapon-on": GAME_CONFIG.colliderTweaker.physicsTest.weaponOn,
  "physics-recently-hit": GAME_CONFIG.colliderTweaker.physicsTest.recentlyHit,
  "physics-self-righting": GAME_CONFIG.colliderTweaker.physicsTest.selfRightingGrace,
  "tweaker-damage-amount": GAME_CONFIG.colliderTweaker.physicalDamage.rawDamage,
  "tweaker-damage-hits": PHYSICAL_DAMAGE_DEFAULTS.significantHitsRequired,
  "tweaker-damage-radius": PHYSICAL_DAMAGE_DEFAULTS.breakRadius,
  "tweaker-damage-match-radius": PHYSICAL_DAMAGE_DEFAULTS.primeMatchRadius,
  "tweaker-damage-max-radius": PHYSICAL_DAMAGE_DEFAULTS.maxBreakRadius,
  "tweaker-damage-max-match-radius": PHYSICAL_DAMAGE_DEFAULTS.maxPrimeMatchRadius,
  "tweaker-damage-max-radius-multiplier": PHYSICAL_DAMAGE_DEFAULTS.maxRadiusDamageMultiplier,
  "tweaker-damage-threshold": PHYSICAL_DAMAGE_DEFAULTS.threshold,
  "tweaker-damage-resilience": PHYSICAL_DAMAGE_DEFAULTS.resilience,
  "tweaker-damage-impulse": PHYSICAL_DAMAGE_DEFAULTS.impulseScale,
  "tweaker-damage-max-pieces": PHYSICAL_DAMAGE_DEFAULTS.maxPiecesPerBot,
  "tweaker-damage-convex": PHYSICAL_DAMAGE_DEFAULTS.convexCollider,
  "physical-damage-view-colliders": GAME_CONFIG.colliderTweaker.physicalDamage.viewColliders,
};
